%% Source Helmut Balzert, Lehrbuch der Software-Technik
%% 2. Auflage, 2000
%% ISBN 3-8274-0480-0
%% Spektrum Akademischer Verlag
%% Seite 1094

%%{
  init: {
    "pie": {
      "textPosition": 0.5
    },
    "themeVariables": {
      "pieOuterStrokeWidth": "1px"
    }
  }
}%%
pie showData
    title Distribution between development and maintenance
    "Development": 20
    "Maintenance": 80
