= The Reactive Manifesto

[The Reactive Manifesto, The authors of the Manifest]
____
Systems built as Reactive Systems are more flexible, loosely-coupled and scalable. This makes them easier to develop and amenable to change. They are significantly more tolerant of failure and when failure does occur they meet it with elegance rather than disaster. Reactive Systems are highly responsive, giving users effective interactive feedback.
____

The Reactive Manifesto describes four fundamental characteristics of scalable systems that are characterised by both high responsiveness and high availability.

A reactive system is characterised by the following key properties:

1. Responsiveness
2. Resilience
3. Flexibility
4. Message-driven

The Reactive Manifesto should not be interpreted as synonymous with reactive programming. The Manifesto describes the characteristics of systems as qualities of a system. It does not specify how these qualities are to be achieved technically.

The manifest can be found at https://reactivemanifesto.org/.

include::partial$why-read-manifests.adoc[leveloffset=+1]